osx_image: xcode8.3
dist: trusty
sudo: required
language: node_js
node_js: 10.11.0
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
os:
- osx
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
script:
- npm run pack
- npm run dist
- cd build && ls
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FMOIbcUDMD/3XV6EJf36KXNZqTpxztMcyfDxDWfi9A0tQDjL9VHf8W+2/7J/LG12jJ+eVI3LditmM0HrhewGvLmSAX1eTmqyvNtAEgY5Zyi0T7wvAAUcTUFwjTFs/aXTycgzxpVUIjT1FHTyqPCBigf3K6VopixoZBXfjO3ogLZxVB1yeijbRbJQMZJ8BNXkvwoFuEjWBLAiQyZ6ytYktZh4HksV8L7W00/oiCFDJNfuY9YCglPMpoVLm8FaLtPBS/FeFZlIE16LuUQOcD6FV4msi2u1mMb34M71UtKXozfR9mIjwvFDo0aHxUx/e2Z6FmQNUEcfXkEThfpV/zNwelfUhtZx/6q8wH670GiI2AYWB2BqcpZ8DaZGrY9iksBXgAJd6LUW3hucHoecv2wjMGi3Z6WG7701hIDw5x8wrUq8HyeJrDnMY6W7/S6SvbqvroT0o2BFMf2ssbn7XeQrp3fuPYZe1nMoxHDPojIdrQlUyhUI1RiRUaPbqS2AVTMiD4G98so1vkVXEQUlzBUNZi5OIim7GjIGshomNuddond//ZLvGi2bS84Yw3pu2ngakGBukAo8YGXRqwDmO38nL7UCOpTTVGoKut8ewefIJ2N1jszk1nbpOxVTNJN0Y5yS6xMmrWeC2tKAULDuQ7TA2v2+l4MlSBL9xOtlRDu6Q6Q=
  file_glob: true
  file: build/*
  on:
    tags: true
